export const HTTP_HELLO_FETCHING = "HTTP_HELLO_FETCHING";
export const HTTP_HELLO_SUCCESS = "HTTP_HELLO_SUCCESS";
export const HTTP_HELLO_FAILED = "HTTP_HELLO_FAILED";
export const HTTP_HELLO_CLEAR = "HTTP_HELLO_CLEAR";
export const HTTP_HELLO_BY_ID_SUCCESS = "HTTP_HELLO_BY_ID_SUCCESS";


export const HTTP_MOVIE_FETCHING = "HTTP_MOVIE_FETCHING";
export const HTTP_MOVIE_SUCCESS = "HTTP_MOVIE_SUCCESS";
export const HTTP_MOVIE_FAILED = "HTTP_MOVIE_FAILED";